# Generated by Django 3.2.24 on 2024-02-29 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='title',
            new_name='complainant_name',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='description',
            new_name='complaint_text',
        ),
    ]
