# Generated by Django 3.2.24 on 2024-02-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_complaint_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='demp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_code', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accept', 'Accepted'), ('reject', 'Rejected')], default='pending', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
