# Generated by Django 3.2.24 on 2024-02-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_auto_20240229_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('complaint_type', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='complaint',
        ),
    ]
