# Generated by Django 3.2.24 on 2024-03-01 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_auto_20240229_2023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Complaints',
            new_name='Complaint',
        ),
    ]
