# Generated by Django 3.2.24 on 2024-03-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_rename_complaints_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accept', 'Accepted'), ('reject', 'Rejected')], default='pending', max_length=10),
        ),
    ]
